title: First Dutch Workshop on AI to combat Financial Crime 
description: The First Dutch Workshop on AI to combat Financial Crime will be held on 6 May 2026 at Science Park, Amsterdam
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
